spring.application.name=streetkart-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/streetkart
spring.datasource.username=macbookair
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
